# Generated by Django 5.2.13 on 2026-04-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OCRDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="documents/")),
                ("extracted_text", models.TextField(blank=True, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("kyc_id", models.CharField(blank=True, max_length=100, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processed", "Processed"),
                            ("needs_review", "Needs Review"),
                            ("failed", "Failed"),
                        ],
                        default="processed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
