# Generated by Django 5.2.13 on 2026-04-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrdocument",
            name="ocr_raw_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
