# Generated by Django 5.2.13 on 2026-04-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0002_ocrdocument_ocr_raw_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrdocument",
            name="parsed_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ocrdocument",
            name="validation_errors",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
