# Generated by Django 5.2.13 on 2026-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr_app", "0003_ocrdocument_parsed_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrdocument",
            name="document_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
